### ISSUE TITLE
Homework Completed

### ISSUE THREAD

**Issue by renestadler** [htl-perg-2019-20-5bhif/docker-wpf-exercise-renestadler#1]
Dear Mr. Stropek!
I'd like to inform you that I have completed this homework.
You can find my ASP.NET-Docker-Image at:
https://hub.docker.com/r/renestadler/dockerwpfsample
Furthermore the WPF-Client in this repository works too
Greetings, 
René Stadler

**Comment by rstropek** [comment]
Well done 👍.

FYI (not relevant for school, just FYI): Since .NET Core 3, you can use `HostBuilder` in WPF apps, too ([sample code](https://github.com/rstropek/Samples/blob/master/CSharpDesignWorkshop/PolygonDesigner/PolygonDesigner/App.xaml.cs)). With this, you get the same nice tools (e.g. dependency injection, `HttpClientFactory`, *appsettings.json*, etc.) as in ASP.NET Core.

Greetings,
Rainer Stropek.
